/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 4
        max_iteration: 5
        filter_size_surf: 0.4
        filter_size_map: 0.2
        cube_side_length: 1000.0
        map_file_path: "Map/mabuk.pcd"

        common:
            lid_topic: "/ouster/points"
            imu_topic: "/ouster/imu"
            odom_topic: "/odom"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0
        preprocess:
            lidar_type: 3
            scan_line: 32
            horizontal_resolution: 512
            timestamp_unit: 3
            blind: 1.5
        localization:
            acc_cov: 1.0
            gyr_cov: 0.01
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree: 360.0
            det_range: 50.0
            extrinsic_est_en: true
            extrinsic_T: [0.0, 0.0, 0.0]
            extrinsic_R: [1.0, 0.0, 0.0,
                        0.0, 1.0, 0.0,
                        0.0, 0.0, 1.0]
            extrinsic_g2o_T: [0.0, 0.0, 0.0]
            extrinsic_g2o_R: [1.0, 0.0, 0.0,
                        0.0, 1.0, 0.0,
                        0.0, 0.0, 1.0]
            keyframe_threshold: 1.0
            odom_mode: 2
            dop_flag: true
        publish:
            path_en: true
            scan_publish_en: true
            dense_publish_en: true
            effect_map_en: true
