/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 4
        max_iteration: 5
        filter_size_surf: 0.4
        filter_size_map: 0.2
        cube_side_length: 1000.0
        map_file_path: "Map/gsic_map.pcd"

        common:
            lid_topic:  "/velodyne_points"
            imu_topic:  "/imu/data"
            odom_topic:  "/scout_base_controller/odom"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0
        
        preprocess:
            lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
            scan_line: 16
            horizontal_resolution: 1800
            timestamp_unit: 2                 # 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
            blind: 0.5

        localization:
            acc_cov: 1.0 
            gyr_cov: 0.01
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     50.0
            extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic
            extrinsic_T: [ 0.0, 0.0, 0.0 ]
            extrinsic_R: [1.0, 0.0, 0.0,
                        0.0, 1.0, 0.0,
                        0.0, 0.0, 1.0]
            extrinsic_g2o_T: [ 0.0, 0.0, 0.0 ]
            extrinsic_g2o_R: [1.0, 0.0, 0.0,
                            0.0, 1.0, 0.0,
                            0.0, 0.0, 1.0]
            keyframe_threshold: 1.0
            odom_mode: 1
            dop_flag: true

        publish:
            path_en:  true
            scan_publish_en:  true       # false: close all the point cloud output
            dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
            effect_map_en: true
